version: '3'
services:
  influxdb:
    image: arm64v8/influxdb:latest
    volumes:
      # Mount for influxdb data directory and configuration
      - ./influxdbv2:/root/.influxdbv2
    ports:
      - "8086:8086"
# Use the influx cli to set up an influxdb instance. 
  influxdb_cli:
    links:
      - influxdb
    image: arm64v8/influxdb:latest
# Use these same configurations parameters in your telegraf configuration, mytelegraf.conf.
    entrypoint: influx setup --bucket Lorax -t tokenconn -o Absys --username=admin --password=Absys,34 --host=http://influxdb:8086 -f
      # Wait for the influxd service in the influxdb container has fully bootstrapped before trying to setup an influxdb instance with the influxdb_cli service. 
    restart: on-failure:10
    depends_on:
      - influxdb
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes: 
      - ./conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
    depends_on:
      - influxdb_cli
    hostname: mqtt    
    container_name: mqtt-influxdb-telegraf_mqtt_1    
  telegraf:
    image: telegraf
    links:
      - influxdb
    volumes:
      # Mount for telegraf config
      - ./conf/telegraf.conf.docker:/etc/telegraf/telegraf.conf
    depends_on:
      - mqtt
  grafana:
    image: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./conf/grafana.ini:/usr/share/grafana/conf/defaults.ini
    depends_on:
      - telegraf
volumes:
  influxdbv2:
